# Generated by Django 5.2.3 on 2026-04-21 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostProperty', '0003_propertylisting_is_verified_inquiry_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertylisting',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property_images/')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_images', to='PostProperty.propertylisting')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
